import random
name = input("Hello brave traveller. I see you hail from a far land. If you do not mind, What is your name")
land = input(name+" The one who is going to save our land, Where do you hail from "+name)
race = input(name+" from "+land+" if I may be so bold you look different from our people, may I ask your race" )
print (name+" the brave,the "+race+" who hails from "+land+" will save us all ")
start = input("Are you ready to being your jounrny "+name+" the brave" )
if start == "yes" or start == "Yes": print(" Brilliant. Now "+name+ " the brave, if you wouldn't mind We would like to see a demonstration of your power")
else : print("As good an answer as any, If you wouldn't mind "+name+" could you please show us a demonstration of your power")
x = input("To cast Fireball, just type Fireball")
firedamage = random.randint(5,11)
if x == "Fireball" or x == "fireball": print("Wowzers "+name+" You just did "+str(firedamage)+" damage to my hat")
else: print("Wowzers "+name+" You just did "+str(firedamage)+" damage to my hat while complaining that you chose not to do Fireball.")
print("Unfortunately Traryars The Wise just took care of our problem. I am Sorry we made you come all this way for nothing.")
